# Generated by Django 4.2.3 on 2023-07-31 20:54

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('OR', 'Ordered')], default='AC', max_length=2),
        ),
        migrations.AlterField(
            model_name='urbannestuser',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
