# Generated by Django 4.2.3 on 2023-08-06 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture', '0002_testimonials_urbannestuser_shopping_cart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='products/')),
                ('price', models.FloatField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('AC', 'Accepted'), ('CA', 'Cancelled'), ('DE', 'Delivered')], default='PE', max_length=2)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Furniture.urbannestuser')),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Furniture.furnituread')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='items',
            field=models.ManyToManyField(to='Furniture.product'),
        ),
    ]
