# Generated by Django 4.2.3 on 2023-07-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture', '0002_remove_orderitem_currency_remove_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('AC', 'Accepted'), ('CA', 'Cancelled'), ('DE', 'Delivered')], default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('AC', 'Accepted'), ('CA', 'Cancelled'), ('DE', 'Delivered')], default='PE', max_length=2),
        ),
    ]
