# Generated by Django 4.2.3 on 2023-08-06 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture', '0003_product_delete_orderitem_alter_shoppingcart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
