# Generated by Django 4.2.3 on 2023-08-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture', '0003_alter_orderitem_status_alter_shoppingcart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnituread',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
