# Generated by Django 4.2.3 on 2023-08-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture', '0004_remove_product_image_remove_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('IC', 'In Shopping Cart'), ('PE', 'Pending'), ('AC', 'Accepted'), ('CA', 'Cancelled'), ('DE', 'Delivered')], default='IC', max_length=2),
        ),
    ]
