# Generated by Django 4.2.3 on 2023-08-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture', '0005_alter_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furnituread',
            name='status',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='status',
        ),
        migrations.AddField(
            model_name='testimonials',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
