# Generated by Django 4.2.3 on 2023-08-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture', '0006_remove_furnituread_status_remove_shoppingcart_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnituread',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
