# Generated by Django 4.2.3 on 2023-08-14 02:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture', '0007_furnituread_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnituread',
            name='currency',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='furnituread',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='furnituread',
            name='unit_weight',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds')], max_length=100),
        ),
    ]
