# Generated by Django 4.2.3 on 2023-08-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture', '0008_alter_furnituread_currency_alter_furnituread_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnituread',
            name='currency',
            field=models.CharField(choices=[('MKD', 'Macedonian Denar'), ('EUR', 'Euro'), ('USD', 'US Dollar')], max_length=3),
        ),
    ]
