# Generated by Django 4.2.3 on 2023-08-14 13:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture', '0010_about_faq_alter_furnituread_currency_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover_page', models.ImageField(blank=True, null=True, upload_to='images/front_cover')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='testimonials',
            old_name='name',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='testimonials',
            old_name='message',
            new_name='quote',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='email',
        ),
        migrations.AddField(
            model_name='testimonials',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonials',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Furniture.urbannestuser'),
            preserve_default=False,
        ),
    ]
