# Generated by Django 4.2.3 on 2023-08-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture', '0012_rename_testimonials_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontcover',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='frontcover',
            name='buy_button',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frontcover',
            name='sell_button',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frontcover',
            name='subtitle',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
