# Generated by Django 4.2.3 on 2023-08-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture', '0013_frontcover_active_frontcover_buy_button_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frontcover',
            old_name='subtitle',
            new_name='subtitle_1',
        ),
        migrations.AddField(
            model_name='frontcover',
            name='subtitle_2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
