# Generated by Django 4.2.3 on 2023-08-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture', '0015_alter_shoppingcart_items_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQ',
            new_name='QNA',
        ),
    ]
